kind: Deployment
apiVersion: apps/v1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
  labels:
    app: ita-power-bi-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ita-power-bi-gateway        
  template:
    metadata:
      labels:
        app: ita-power-bi-gateway
    spec:
      containers:
      - name: ita-power-bi-gateway
        image: itasharedappregistryprodeast1.azurecr.io/ita-powerbi-gateway:#{Release.Artifacts._InternationalTradeAdministration.ita-powerbi-gateway.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: POWERBI_TENANT_ID
            value: #{TENANT-ID}#
          - name: POWERBI_CLIENT_ID
            value: #{POWERBI-CLIENT-ID}#
          - name: POWERBI_CLIENT_SECRET
            value: #{POWERBI-CLIENT-SECRET}#
          - name: FLYWAY_URL
            value: #{FLYWAY-URL-PROD}#
          - name: FLYWAY_USER
            value: #{FLYWAY-USER-PROD}#
          - name: FLYWAY_PASSWORD
            value: "#{FLYWAY-PASSWORD-PROD}#"
          - name: GATEWAY_API_TOKEN
            value: #{GATEWAY-API-TOKEN}#
          - name: BUILD_ID
            value: "#{Release.Artifacts._InternationalTradeAdministration.ita-powerbi-gateway.BuildId}#"
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: ita-power-bi-gateway
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  name: ita-power-bi-gateway
  namespace: mdsnamespace
spec:
  rules:
    - host: powerbi.trade.gov
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: ita-power-bi-gateway
                port:
                  number: 80
  tls:
    - hosts:
        - powerbi.trade.gov
      secretName: trade-gov-tls-secret
