CREATE OR ALTER PROCEDURE sp_OTEXA_POST_PROCESSING
AS
BEGIN
   TRUNCATE TABLE OTEXA_COUNTRY_REF
   INSERT INTO [OTEXA_COUNTRY_REF] ([CTRY_DESCRIPTION], [SOURCE])
   SELECT DISTINCT Country, 'ANNUAL' FROM [dbo].[OTEXA_ANNUAL] UNION ALL
   SELECT DISTINCT Country, 'ANNUAL_FOOTWEAR' FROM [dbo].[OTEXA_ANNUAL_FOOTWEAR] UNION ALL
   SELECT DISTINCT COUNTRY, 'EXPORT' FROM [dbo].[OTEXA_EXPORTS] UNION ALL
   SELECT DISTINCT Country, 'EXPORT_FOOTWEAR' FROM [dbo].[OTEXA_EXPORT_FOOTWEAR]

   TRUNCATE TABLE OTEXA_HTS_CAT_REF
   INSERT INTO OTEXA_HTS_CAT_REF ([HTS], [CAT_ID])
   SELECT DISTINCT [HTS], [CAT_ID] from OTEXA_ANNUAL union
   SELECT DISTINCT [HTS], [CAT_ID] from OTEXA_ANNUAL_FOOTWEAR union
   SELECT DISTINCT [SCHEDULE_B], [CAT_ID] FROM OTEXA_EXPORT_FOOTWEAR

   TRUNCATE TABLE [dbo].[OTEXA_HTS_CHAPTER_REF]
   INSERT INTO [dbo].[OTEXA_HTS_CHAPTER_REF] (CAT_ID, CHAPTER, HTS)
   SELECT DISTINCT CAT_ID, SUBSTRING(HTS, 1, 2) as CHAPTER, HTS FROM OTEXA_ANNUAL UNION
   SELECT DISTINCT CAT_ID, SUBSTRING(HTS, 1, 2) as CHAPTER, HTS FROM OTEXA_ANNUAL_FOOTWEAR UNION
   SELECT DISTINCT CAT_ID, SUBSTRING(SCHEDULE_B, 1, 2) as CHAPTER, SCHEDULE_B FROM OTEXA_EXPORT_FOOTWEAR
END
GO
