CREATE OR ALTER VIEW [dbo].[OTEXA_COUNTRY_REF_VW]
AS
SELECT
    [OTEXA_COUNTRY_REF].[CTRY_ID],
    [OTEXA_COUNTRY_GROUPS].[CTRYNUMBER] as 'CTRY_NUMBER',
    [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION],
    [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] as 'CTRY_GROUP',
    [OTEXA_COUNTRY_REF].[SOURCE]
FROM [dbo].[OTEXA_COUNTRY_REF] INNER JOIN [dbo].[OTEXA_COUNTRY_GROUPS]
ON [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION] = [OTEXA_COUNTRY_GROUPS].[COUNTRY_ABBR_ANNUAL]
WHERE [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] IS NOT NULL

UNION

SELECT
    [OTEXA_COUNTRY_REF].[CTRY_ID],
    [OTEXA_COUNTRY_GROUPS].[CTRYNUMBER] as 'CTRY_NUMBER',
    [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION],
    [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] as 'CTRY_GROUP',
    [OTEXA_COUNTRY_REF].[SOURCE]
FROM [dbo].[OTEXA_COUNTRY_REF] INNER JOIN [dbo].[OTEXA_COUNTRY_GROUPS]
ON [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION] = [OTEXA_COUNTRY_GROUPS].[COUNTRY]
WHERE [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] IS NOT NULL

UNION

SELECT
    [OTEXA_COUNTRY_REF].[CTRY_ID],
    [OTEXA_COUNTRY_GROUPS].[CTRYNUMBER] as 'CTRY_NUMBER',
    [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION],
    [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] as 'CTRY_GROUP',
    [OTEXA_COUNTRY_REF].[SOURCE]
FROM [dbo].[OTEXA_COUNTRY_REF] INNER JOIN [dbo].[OTEXA_COUNTRY_GROUPS]
ON [OTEXA_COUNTRY_REF].[CTRY_DESCRIPTION] = [OTEXA_COUNTRY_GROUPS].[ALT_COUNTRY_ABBR]
WHERE [OTEXA_COUNTRY_GROUPS].[COUNTRYGROUP] IS NOT NULL

GO
