CREATE OR ALTER VIEW gm_hr_reader.GMHR_DH_INPUT_TABLE
AS
SELECT * FROM [dbo].[GMHR_DH_INPUT_TABLE]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_LES_INPUT_TABLE
AS
SELECT * FROM [dbo].[GMHR_LES_INPUT_TABLE]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_DH_PROJECTIONS
AS
SELECT * FROM [dbo].[GMHR_DH_PROJECTIONS]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_LES_PROJECTIONS
AS
SELECT * FROM [dbo].[GMHR_LES_PROJECTIONS]
GO

CREATE OR ALTER VIEW gm_hr_reader.GM_HR_FUNDS_TABLE
AS
SELECT * FROM [dbo].[GM_HR_FUNDS_TABLE]
GO