CREATE OR ALTER PROCEDURE sp_OTEXA_EXPORT_POST_PROCESSING
AS
BEGIN
   TRUNCATE TABLE OTEXA_SCHEDULEB_GROUP_REF
   INSERT INTO OTEXA_SCHEDULEB_GROUP_REF([SCHEDULE_B], [GROUP_ID])
   SELECT DISTINCT [SCHEDB], [GROUP] from OTEXA_EXPORTS

   TRUNCATE TABLE OTEXA_SCHEDULEB_CAT_REF
   INSERT INTO OTEXA_SCHEDULEB_CAT_REF([SCHEDULE_B], [CAT_ID])
   SELECT DISTINCT [SCHEDULE_B], [CAT_ID] from OTEXA_EXPORT_FOOTWEAR

   TRUNCATE TABLE [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF]
   INSERT INTO [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF] (GROUP_ID, CHAPTER, SCHEDULE_B, CAT_ID, SOURCE)
   SELECT DISTINCT [GROUP], SUBSTRING(SCHEDB, 1, 2) as CHAPTER, SCHEDB, null, 'EXPORT' FROM OTEXA_EXPORTS UNION
   SELECT DISTINCT null, SUBSTRING(SCHEDULE_B, 1, 2) as CHAPTER, SCHEDULE_B, [CAT_ID], 'EXPORT_FOOTWEAR' FROM OTEXA_EXPORT_FOOTWEAR
END
GO

DROP VIEW IF EXISTS [dbo].[OTEXA_SCHEDULEB_REF_VW]
GO

CREATE VIEW [dbo].[OTEXA_SCHEDULEB_REF_VW]
AS
    SELECT schedb_chapter.[SCHEDULE_B]
         , schedb_group.[GROUP_ID]
         , schedb_cat.[CAT_ID]
         , CONCAT(schedb_chapter.[SCHEDULE_B], ' - ', schedb.[DESCRIPTION]) as 'LONG_SCHEDB'
    FROM [dbo].[OTEXA_SCHEDULEB_REF] schedb
    RIGHT OUTER JOIN [dbo].[OTEXA_SCHEDULEB_GROUP_REF] schedb_group
      ON schedb.SCHEDULE_B = schedb_group.SCHEDULE_B
    RIGHT OUTER JOIN [dbo].[OTEXA_SCHEDULEB_CAT_REF] schedb_cat
      ON schedb.SCHEDULE_B = schedb_cat.SCHEDULE_B
    RIGHT OUTER JOIN [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF] schedb_chapter
      ON schedb.SCHEDULE_B = schedb_chapter.SCHEDULE_B
GO


DROP VIEW IF EXISTS [dbo].[OTEXA_GROUP_REF_VW]
GO

CREATE VIEW [OTEXA_GROUP_REF_VW]
AS
    SELECT *, CONCAT([GROUP_ID], ' - ', [GROUP_DESCRIPTION]) as 'LONG_GROUP'
    FROM [dbo].[OTEXA_GROUP_REF]
GO


DROP VIEW IF EXISTS [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF_VW]
GO

CREATE VIEW [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF_VW]
AS
    SELECT DISTINCT mapping.GROUP_ID
        , schedb_cat.CAT_ID
        , mapping.SCHEDULE_B
        , CONCAT(mapping.[SCHEDULE_B], ' - ', schedb.[DESCRIPTION]) as 'LONG_SCHEDB'
        , mapping.CHAPTER
        , CONCAT(mapping.[CHAPTER], ' - ', c.[CHAPTER_DESCRIPTION]) as 'LONG_CHAPTER'
        , mapping.SOURCE
    FROM OTEXA_SCHEDULEB_CHAPTER_REF mapping
    LEFT OUTER JOIN OTEXA_CHAPTER_REF c
        ON mapping.CHAPTER = c.CHAPTER
    LEFT OUTER JOIN OTEXA_SCHEDULEB_CAT_REF schedb_cat
        ON mapping.SCHEDULE_B = schedb_cat.SCHEDULE_B
        AND mapping.CAT_ID = schedb_cat.CAT_ID
    LEFT OUTER JOIN OTEXA_SCHEDULEB_REF schedb
        ON mapping.SCHEDULE_B = schedb.[SCHEDULE_B]
        AND (mapping.GROUP_ID = schedb.GROUP_ID
            OR mapping.SOURCE = 'EXPORT_FOOTWEAR')
GO
