CREATE OR ALTER VIEW gm_hr_reader.GMHR_DH_FLAT_FILE
AS
SELECT * FROM [dbo].[GMHR_DH_FLAT_FILE]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_LES_FLAT_FILE
AS
SELECT * FROM [dbo].[GMHR_LES_FLAT_FILE]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_DH_PROJECTIONS
AS
SELECT * FROM [dbo].[GMHR_DH_PROJECTIONS]
GO

CREATE OR ALTER VIEW gm_hr_reader.GMHR_LES_PROJECTIONS
AS
SELECT * FROM [dbo].[GMHR_LES_PROJECTIONS]
GO