CREATE OR ALTER PROCEDURE sp_OTEXA_EXPORT_POST_PROCESSING
AS
BEGIN
   TRUNCATE TABLE OTEXA_SCHEDULEB_GROUP_REF
   INSERT INTO OTEXA_SCHEDULEB_GROUP_REF([SCHEDULE_B], [GROUP_ID])
   SELECT DISTINCT [SCHEDB], [GROUP] from OTEXA_EXPORTS

   TRUNCATE TABLE [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF]
   INSERT INTO [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF] (GROUP_ID, CHAPTER, SCHEDULE_B)
   SELECT DISTINCT [GROUP], SUBSTRING(SCHEDB, 1, 2) as CHAPTER, SCHEDB FROM OTEXA_EXPORTS
END
GO

CREATE OR ALTER PROCEDURE sp_OTEXA_EXPORT_FOOTWEAR_POST_PROCESSING
AS
BEGIN
   TRUNCATE TABLE OTEXA_SCHEDULEB_CAT_REF
   INSERT INTO OTEXA_SCHEDULEB_CAT_REF([SCHEDULE_B], [CAT_ID])
   SELECT DISTINCT [SCHEDULE_B], [CAT_ID] from OTEXA_EXPORT_FOOTWEAR

   TRUNCATE TABLE [dbo].[OTEXA_SCHEDULEB_CHAPTER_CATEGORY_REF]
   INSERT INTO [dbo].[OTEXA_SCHEDULEB_CHAPTER_CATEGORY_REF] (CAT_ID, CHAPTER, SCHEDULE_B)
   SELECT DISTINCT [CAT_ID], SUBSTRING(SCHEDULE_B, 1, 2) as CHAPTER, SCHEDULE_B FROM OTEXA_EXPORT_FOOTWEAR
END
GO

DROP VIEW IF EXISTS [dbo].[OTEXA_SCHEDULEB_REF_VW]
GO

CREATE VIEW [dbo].[OTEXA_SCHEDULEB_REF_VW]
AS
    SELECT schedb.[SCHEDULE_B], schedb_group.[GROUP_ID], schedb_cat.[CAT_ID], CONCAT(schedb.[SCHEDULE_B], ' - ', schedb.[DESCRIPTION]) as 'LONG_SCHEDB'
    FROM [dbo].[OTEXA_SCHEDULEB_REF] schedb
    INNER JOIN [dbo].[OTEXA_SCHEDULEB_GROUP_REF] schedb_group
      ON schedb.SCHEDULE_B = schedb_group.SCHEDULE_B
    INNER JOIN [dbo].[OTEXA_SCHEDULEB_CAT_REF] schedb_cat
      ON schedb.SCHEDULE_B = schedb_cat.SCHEDULE_B
GO


DROP VIEW IF EXISTS [dbo].[OTEXA_GROUP_REF_VW]
GO

CREATE VIEW [OTEXA_GROUP_REF_VW]
AS
    SELECT *, CONCAT([GROUP_ID], ' - ', [GROUP_DESCRIPTION]) as 'LONG_GROUP'
    FROM [dbo].[OTEXA_GROUP_REF]
GO


DROP VIEW IF EXISTS [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF_VW]
GO

CREATE VIEW [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF_VW]
AS
    SELECT mapping.GROUP_ID
        , OTEXA_SCHEDULEB_CAT_REF.CAT_ID
        , mapping.SCHEDULE_B
        , mapping.CHAPTER
        , CONCAT(c.[CHAPTER], ' - ', c.[CHAPTER_DESCRIPTION]) as 'LONG_CHAPTER'
    FROM OTEXA_SCHEDULEB_CHAPTER_REF mapping
    INNER JOIN OTEXA_CHAPTER_REF c
        ON mapping.CHAPTER = c.CHAPTER
    INNER JOIN OTEXA_SCHEDULEB_CAT_REF
        ON OTEXA_SCHEDULEB_CAT_REF.SCHEDULE_B = mapping.SCHEDULE_B
GO
