DROP TABLE IF EXISTS [dbo].[CTO_BOC_MAPPING]
GO

CREATE TABLE [dbo].[CTO_BOC_MAPPING]
(
    [Sub-BOC] VARCHAR(MAX),
    [Sub-BOC Description]   VARCHAR(MAX),
    [IT Cost Pools] VARCHAR(MAX),
    [IT Cost Sub-Pools] VARCHAR(MAX)
)
GO

DROP TABLE IF EXISTS [dbo].[CTO_ALL_FUNDS]
GO

CREATE TABLE [dbo].[CTO_ALL_FUNDS]
(
    BC  INTEGER,
    FC  INTEGER,
    FCFY    INTEGER,
    [TREAS SYM] VARCHAR(MAX),
    FY  INTEGER,
    PROJECT VARCHAR(MAX),
    TASK    VARCHAR(MAX),
    [Project Type]  VARCHAR(MAX),
    [ACCOUNT]   INTEGER,
    TRANS_NO    INTEGER,
    TRANS_DATE  DATETIME,
    GL_END_DATE DATETIME,
    TRANS_CODE  VARCHAR(MAX),
    TRANS_SOURCE    VARCHAR(MAX),
    USER_NAME   VARCHAR(MAX),
    SUBSYSTEM   VARCHAR(MAX),
    DEBIT_AMOUNT    VARCHAR(MAX),
    CREDIT_AMOUNT   VARCHAR(MAX),
    [CR-DR AMOUNT]  VARCHAR(MAX),
    REFERENCE_NO    VARCHAR(MAX),
    BOC VARCHAR(MAX),
    OC1 INTEGER,
    OC2 INTEGER,
    OC3 INTEGER,
    OC4 INTEGER,
    ORG1    INTEGER,
    ORG2    INTEGER,
    ORG3    INTEGER,
    ORG4    INTEGER,
    ORG5    INTEGER,
    ORG6    INTEGER,
    ORG7    INTEGER,
    PROG1   INTEGER,
    PROG2   INTEGER,
    PROG3   INTEGER,
    PROG4   INTEGER,
    DOCUMENT_TYPE   VARCHAR(MAX),
    VENDOR_NO   BIGINT,
    [VENDOR NAME] VARCHAR(MAX),
    [P Org1 Code]   INTEGER,
    [P Org2 Code]   INTEGER,
    [P Org3 Code]   INTEGER,
    [P Org4 Code]   INTEGER,
    [P Org5 Code]   INTEGER,
    [P Org6 Code]   INTEGER,
    [P Org7 Code]   INTEGER
)