IF NOT EXISTS(SELECT 1
              FROM sys.indexes
              WHERE Name = N'OTEXA_MONTHLY_FOOTWEAR_EXPORTS_ON_YR'
                AND Object_ID = OBJECT_ID(N'dbo.OTEXA_MONTHLY_FOOTWEAR_EXPORTS'))
CREATE NONCLUSTERED INDEX OTEXA_MONTHLY_FOOTWEAR_EXPORTS_ON_YR
    ON [dbo].[OTEXA_MONTHLY_FOOTWEAR_EXPORTS] (YR)
