IF NOT EXISTS(SELECT 1
              FROM sys.columns
              WHERE Name = N'CREATED_AT'
                AND Object_ID = OBJECT_ID(N'dbo.OTEXA_MONTHLY_FOOTWEAR_EXPORTS'))
    BEGIN
        TRUNCATE TABLE [dbo].[OTEXA_MONTHLY_FOOTWEAR_EXPORTS]
        ALTER TABLE [dbo].[OTEXA_MONTHLY_FOOTWEAR_EXPORTS]
            ADD [CREATED_AT] datetime NOT NULL
        CREATE NONCLUSTERED INDEX OTEXA_MONTHLY_FOOTWEAR_EXPORTS_ON_CREATED_AT
            ON [dbo].[OTEXA_MONTHLY_FOOTWEAR_EXPORTS] (CREATED_AT)
    END
