DROP VIEW IF EXISTS [dbo].[GMHR_LES_OUTPUT_VIEW]

DROP TABLE IF EXISTS [dbo].[GMHR_DH_FLAT_FILE]

DROP VIEW IF EXISTS gm_hr_reader.GMHR_DH_FLAT_FILE

DROP TABLE IF EXISTS [dbo].[GMHR_LES_FLAT_FILE]

DROP VIEW IF EXISTS gm_hr_reader.GMHR_LES_FLAT_FILE

DROP TABLE IF EXISTS [dbo].[GMHR_DH_FLAT_FILE]

DROP VIEW IF EXISTS [dbo].[GMHR_DH_OUTPUT_VIEW]