DROP TABLE IF EXISTS [dbo].[OTEXA_SCHEDULEB_REF]
CREATE TABLE [dbo].[OTEXA_SCHEDULEB_REF](
	[GROUP_ID]            [varchar](3) NULL,
	[SCHEDULE_B]          [varchar](25) NULL,
	[DESCRIPTION]         [varchar](255) NULL
)
GO


DROP TABLE IF EXISTS [dbo].[OTEXA_GROUP_REF]
CREATE TABLE [dbo].[OTEXA_GROUP_REF](
	[GROUP_ID]            [varchar](3) NULL,
	[GROUP_DESCRIPTION]   [varchar](255) NULL
)
GO

DROP TABLE IF EXISTS OTEXA_SCHEDULEB_GROUP_REF
CREATE TABLE OTEXA_SCHEDULEB_GROUP_REF (
	[SCHEDULE_B]          [varchar](25) NULL,
	[GROUP_ID]            [varchar](3) NULL,
)
GO


DROP TABLE IF EXISTS [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF]
CREATE TABLE [dbo].[OTEXA_SCHEDULEB_CHAPTER_REF](
	[CHAPTER]     [varchar](25) NULL,
	[SCHEDULE_B]  [varchar](25) NULL,
	[GROUP_ID]    [varchar](3) NULL
)
GO
