DROP TABLE IF EXISTS [dbo].[TRAVEL_INDICATORS_MONTHLY]

CREATE TABLE [dbo].[TRAVEL_INDICATORS_MONTHLY] (
    Year                                     nvarchar(25),
    Month_Number                             nvarchar(25),
    Month_Abbr                               nvarchar(25),
    Month_Letter                             nvarchar(25),
    Visitors                                 nvarchar(25),
    Visitors_Change                          nvarchar(25),
    Travel_Exports                           nvarchar(25),
    Travel_Exports_Change                    nvarchar(25),
    Travel_Trade_Balance                     nvarchar(25),
    Travel_Trade_Balance_Change              nvarchar(25),
    ESTA_FEES_Collected                      nvarchar(25),
    ESTA_FEES_Collected_Change               nvarchar(25),
    ESTA_FEES_12_Month_Moving_Sum            nvarchar(25),
    Visa_Interview_Wait_Time_Brasilia        nvarchar(25),
    Visa_Interview_Wait_Time_Recife          nvarchar(25),
    Visa_Interview_Wait_Time_Rio_de_Janeiro  nvarchar(25),
    Visa_Interview_Wait_Time_Sao_Paulo       nvarchar(25),
    Visa_Interview_Wait_Time_Porto_Alegre    nvarchar(25),
    Visa_Interview_Wait_Time_Beijing         nvarchar(25),
    Visa_Interview_Wait_Time_Chengdu         nvarchar(25),
    Visa_Interview_Wait_Time_Guangzhuo       nvarchar(25),
    Visa_Interview_Wait_Time_Shanghai        nvarchar(25),
    Visa_Interview_Wait_Time_Shenyang        nvarchar(25),
    Visa_Interview_Wait_Time_Chennai         nvarchar(25),
    Visa_Interview_Wait_Time_Hyderabad       nvarchar(25),
    Visa_Interview_Wait_Time_Kolkata         nvarchar(25),
    Visa_Interview_Wait_Time_Mumbai          nvarchar(25),
    Visa_Interview_Wait_Time_New_Delhi       nvarchar(25),
    Brazil                                   nvarchar(25),
    China                                    nvarchar(25),
    India                                    nvarchar(25),
    South_Korea                              nvarchar(25),
    Japan                                    nvarchar(25),
    UK                                       nvarchar(25),
    Germany                                  nvarchar(25),
    France                                   nvarchar(25),
    Professionalism                          nvarchar(25),
    Efficiency                               nvarchar(25),
    Friendliness                             nvarchar(25),
    Welcoming                                nvarchar(25),
    Time_To_Clear_Passport_Control           nvarchar(25),
    Time_To_Clear_Passport_Control_Is_Long   nvarchar(25),
    Time_To_Clear_Passport_Control_Not_Long  nvarchar(25),
    Time_To_Get_Bags                         nvarchar(25),
    Time_To_Get_Bags_Is_Long                 nvarchar(25),
    Time_To_Get_Bags_Not_Long                nvarchar(25),
    Time_To_Clear_Customs                    nvarchar(25),
    Time_To_Clear_Customs_Is_Long            nvarchar(25),
    Time_To_Clear_Customs_Not_Long           nvarchar(25),
    US_Entry_Experience_Rating               nvarchar(25),
    Sum_of_Mean_Wait_Times                   nvarchar(25)
)

DROP TABLE IF EXISTS [dbo].[TRAVEL_INDICATORS_ANNUAL]
CREATE TABLE [dbo].[TRAVEL_INDICATORS_ANNUAL] (
    Year                              nvarchar(25),
    BLS_Total_Employment              nvarchar(25),
    BLS_Total_Employment_Change       nvarchar(25),
    BEA_TT_Employment                 nvarchar(25),
    BEA_Travel_Employment_Change      nvarchar(25),
    Real_GDP_Output_Change            nvarchar(25),
    Real_TT_Output_Change             nvarchar(25),
    B1_B2_Visas_Issued_Brazil         nvarchar(25),
    B1_B2_Visas_Issued_China          nvarchar(25),
    B1_B2_Visas_Issued_India          nvarchar(25),
    B1_B2_Visas_Issued_Rest_of_World  nvarchar(25),
    Visitor_Volume                    nvarchar(25),
    Total_USA                         nvarchar(25),
    Brazil                            nvarchar(25),
    China                             nvarchar(25),
    India                             nvarchar(25)
)
