CREATE TABLE [imau_adcvd].[SEGMENTS]
(
    internal_id                                 [bigint] IDENTITY NOT NULL,
    Id                                          [nvarchar](18)    NOT NULL,
    OwnerId                                     [nvarchar](18)    NOT NULL,
    IsDeleted                                   [bit]             NOT NULL,
    Name                                        [nvarchar](18)    NOT NULL,
    CreatedDate                                 [smalldatetime]   NOT NULL,
    CreatedById                                 [nvarchar](18)    NOT NULL,
    LastModifiedDate                            [smalldatetime],
    LastModifiedById                            [nvarchar](18),
    SystemModstamp                              [smalldatetime],
    Access_Barcode__c                           [nvarchar](255),
    Actual_Amend_Final_Concurrence_to_DAS__c    [smalldatetime],
    Actual_Amend_Final_Issues_to_DAS__c         [smalldatetime],
    Actual_Amended_Final_Signature__c           [smalldatetime],
    Actual_Date_of_Decision_on_HoP__c           [smalldatetime],
    Actual_Decision_on_HOP_Concurrence_toDAS__c [smalldatetime],
    Actual_Decision_on_HOP_Issues_to_DAS__c     [smalldatetime],
    Actual_Final_Concurrence_to_DAS__c          [smalldatetime],
    Actual_Final_Issues_to_DAS__c               [smalldatetime],
    Actual_Final_Signature__c                   [smalldatetime],
    Actual_Initiation_Concurrence_to_DAS__c     [smalldatetime],
    Actual_Initiation_Issues_to_DAS__c          [smalldatetime],
    Actual_Initiation_Signature__c              [smalldatetime],
    Actual_Prelim_Concurrence_to_DAS__c         [smalldatetime],
    Actual_Prelim_Issues_to_DAS__c              [smalldatetime],
    Actual_Preliminary_Signature__c             [smalldatetime],
    Actual_Revocation_or_Continuation_FR__c     [smalldatetime],
    ADCVD_Case__c                               [nvarchar](18),
    ADCVD_Case_Number__c                        [nvarchar](255),
    ADCVD_Case_Number_Text__c                   [nvarchar](255),
    ADCVD_Case_Type__c                          [nvarchar](255),
    ADCVD_Case_Type_Text__c                     [nvarchar](255),
    ADCVD_Order__c                              [nvarchar](255),
    Adequacy_Determination_Letter__c            [smalldatetime],
    Adequacy_Determination_Letter_to_ITC__c     [smalldatetime],
    Adequacy_of_Respondents_Submission__c       [nvarchar](255),
    Adequate_after_Determination__c             [nvarchar](255),
    Adequate_after_Reconsideration__c           [nvarchar](255),
    Administrative_Review_Aligned_To__c         [nvarchar](18),
    All_parties_in_agreement_to_the_outcome__c  [nvarchar](255),
    Amend_Final_Concurrence_Due_to_DAS__c       [smalldatetime],
    Amend_Final_Issues_Due_to_DAS__c            [smalldatetime],
    Amended_Final_Announcement_Date__c          [smalldatetime],
    Anniversary_Month__c                        [nvarchar](9),
    Announcement_Type__c                        [nvarchar](255),
    Application_Accepted__c                     [smalldatetime],
    Application_Properly_Filed_and_Served__c    [smalldatetime],
    Calculated_Amended_Final_Signature__c       [smalldatetime],
    Calculated_Final_FR_Signature__c            [smalldatetime],
    Calculated_Final_Signature__c               [smalldatetime],
    Calculated_Initiation_Signature__c          [smalldatetime],
    Calculated_Preliminary_Signature__c         [smalldatetime],
    Calculated_Revocation_or_Continuation_FR__c [smalldatetime],
    Case_Briefs_Due__c                          [smalldatetime],
    Case_Concat_Text_Values__c                  [nvarchar](255),
    CBP_Case_Number__c                          [nvarchar](255),
    CBP_Case_Number_Text__c                     [nvarchar](255),
    Choose_Following_Respondent_Selection__c    [nvarchar](255),
    Comments_on_Adequacy_Determination_Filed__c [smalldatetime],
    Commodity__c                                [nvarchar](255),
    Commodity_Text__c                           [nvarchar](255),
    Continuation_or_Revocation__c               [nvarchar](255),
    Countervailed_Programs__c                   [nvarchar](max),
    Country__c                                  [nvarchar](255),
    Country_Text__c                             [nvarchar](255),
    Country_in_which_factors_were_valued__c     [nvarchar](255),
    Days_Remaining__c                           [nvarchar](255),
    Deadline_for_Decision_on_How_to_Proceed__c  [smalldatetime],
    Decision_on_HOP_Concurrence_Due_to_DAS__c   [smalldatetime],
    Decision_on_HOP_Issues_Due_to_DAS__c        [smalldatetime],
    Decision_on_How_to_Proceed__c               [nvarchar](255),
    Decision_Signed__c                          [bit],
    Deficient_or_Withdrawn_Date__c              [smalldatetime],
    Do_Delete__c                                [bit],
    Does_the_Review_Involve_CCR__c              [nvarchar](255),
    Domestic_Party_File_Substan_Response__c     [nvarchar](255),
    Effective_Date_if_revoked__c                [smalldatetime],
    External_Id__c                              [nvarchar](255),
    Final_Announcement_Date__c                  [smalldatetime],
    Final_Concurrence_Due_to_DAS__c             [smalldatetime],
    Final_Date_of_Anniversary_Month__c          [smalldatetime],
    Final_Extension_of_days__c                  [decimal](18, 0),
    Final_Extension_Remaining__c                [smallint],
    Final_Issues_Due_to_DAS__c                  [smalldatetime],
    Final_Team_Meeting_Deadline__c              [smalldatetime],
    Have_Custom_Instruction_been_sent__c        [nvarchar](255),
    Hearing_if_Requested__c                     [smalldatetime],
    HTS_Changes__c                              [nvarchar](25),
    Inadequate_Domestic_Response_note_to_ITC__c [smalldatetime],
    Inform_Cluster_Coordinator_if_No_Respons__c [smalldatetime],
    Initiation_Announcement_Date__c             [smalldatetime],
    Initiation_Concurrence_Due_to_DAS__c        [smalldatetime],
    Initiation_Extension_of_days__c             [decimal](18, 0),
    Initiation_Extension_Remaining__c           [smallint],
    Initiation_Issues_Due_to_DAS__c             [smalldatetime],
    Injunction__c                               [nvarchar](255),
    Intent_to_Participate_by_Domestic_IPs__c    [nvarchar](255),
    Investigation__c                            [nvarchar](18),
    Is_the_review_being_rescinded__c            [nvarchar](255),
    Is_this_review_expedited__c                 [nvarchar](255),
    Issue_Liquidation_Revocation_Instruction__c [smalldatetime],
    ITC_Vote_on_Continuation_or_Revocation__c   [smalldatetime],
    Link__c                                     [nvarchar](500),
    Litigation_Hold_Expiration_Date__c          [smalldatetime],
    Litigation_Resolved__c                      [nvarchar](255),
    Litigation_Status__c                        [nvarchar](255),
    Litigation_YesNo__c                         [nvarchar](255),
    Locked__c                                   [bit],
    Lotus_Notes_History_Data__c                 [nvarchar](max),
    Lotus_Notes_Litigation_ID__c                [nvarchar](250),
    Memorandum_on_Adequacy_Determination__c     [smalldatetime],
    Minesterial_Error_for_final__c              [nvarchar](255),
    New_Shipper_Sync_Level__c                   [nvarchar](255),
    Next_Announcement_Date__c                   [smalldatetime],
    Next_Due_to_DAS_Deadline__c                 [smalldatetime],
    Next_Major_Deadline__c                      [smalldatetime],
    Next_Office_Deadline__c                     [smalldatetime],
    Notice_of_Intent_to_Participate__c          [smalldatetime],
    Notice_of_intent_to_participate_Ips__c      [nvarchar](255),
    Notification_of_ITC_of_Inadequate_Resp__c   [smalldatetime],
    Notify_Cluster_Coordinator_No_Interest__c   [smalldatetime],
    Notify_ITC_If_Affirmative_Prelim_Determ__c  [smalldatetime],
    Notify_ITC_of_Final_Results__c              [smalldatetime],
    Notify_ITC_of_No_Domestic_Interest__c       [smalldatetime],
    Number_of_Companies_Requested__c            [decimal](18, 0),
    Number_of_Mandatory_Companies__c            [decimal](18, 0),
    Number_of_SR_Companies__c                   [decimal](18, 0),
    Office__c                                   [nvarchar](10),
    Period_Covered_End_Date__c                  [smalldatetime],
    Period_Covered_Start_Date__c                [smalldatetime],
    Prelim_Concurrence_Due_to_DAS__c            [smalldatetime],
    Prelim_Extension__c                         [decimal](18, 0),
    Prelim_Issues_Due_to_DAS__c                 [smalldatetime],
    Prelim_Team_Meeting_Deadline__c             [smalldatetime],
    Preliminary_Announcement_Date__c            [smalldatetime],
    Preliminary_Determination__c                [nvarchar](255),
    Preliminary_Extension_Remaining__c          [smallint],
    Product__c                                  [nvarchar](255),
    Product_Description__c                      [nvarchar](50),
    Product_Short_Name__c                       [nvarchar](255),
    Product_Short_Name_Text__c                  [nvarchar](255),
    Product_Short_Name_Text_Value__c            [nvarchar](255),
    Product_Text__c                             [nvarchar](255),
    Product_Text_Value__c                       [nvarchar](255),
    Range_of_Rates_Final__c                     [nvarchar](255),
    Range_of_Rates_Prelim__c                    [nvarchar](255),
    Rebuttal_Briefs_Due__c                      [smalldatetime],
    Rebuttal_Comments_Due__c                    [smalldatetime],
    Receive_Request_to_Consider_Sampling__c     [nvarchar](255),
    RecordTypeId                                [nvarchar](18),
    Request_Filed__c                            [smalldatetime],
    Requestor__c                                [nvarchar](18),
    Respondent_File_Substantive_Response__c     [nvarchar](255),
    Review_to_address_zeroing_in_Segments__c    [nvarchar](255),
    Schedule_Refresh__c                         [bit],
    Scope_Determination__c                      [nvarchar](max),
    Scope_Language_Changes__c                   [nvarchar](max),
    Segment_Name__c                             [nvarchar](255),
    Segment_Outcome__c                          [nvarchar](255),
    Status__c                                   [nvarchar](255),
    Substantive_Response_Due_For_All_Parties__c [smalldatetime],
    Sunset_Review_Type__c                       [nvarchar](255),
    Suspension_Agreement__c                     [nvarchar](18),
    Tolling_Update__c                           [bit],
    Type_of_Circumvention_Inquiry__c            [nvarchar](255),
    Type_of_Requestor__c                        [nvarchar](255),
    Type_of_Scope_Ruling__c                     [nvarchar](255),
    Update_ACE_Customs_Module__c                [smalldatetime],
    Verification_if_needed__c                   [smalldatetime],
    Was_product_determined_to_be_in_scope__c    [nvarchar](255),
    Was_Product_Prelim_Determine_in_Scope__c    [nvarchar](255),
    Was_Product_Prelim_Determine_on_Scope__c    [nvarchar](255),
    What_to_Use_For_Respondent_Selection__c     [nvarchar](255),
    Will_you_Amend_the_Final__c                 [nvarchar](255),
)

ALTER TABLE [imau_adcvd].[SEGMENTS]
    ADD CONSTRAINT [pk_segments_on_internal_id] PRIMARY KEY CLUSTERED ([internal_id] ASC)

CREATE UNIQUE NONCLUSTERED INDEX [index_segments_on_id] ON [imau_adcvd].[SEGMENTS]
    ([Id] ASC)

CREATE NONCLUSTERED INDEX [index_segments_on_status__c] ON [imau_adcvd].[SEGMENTS]
    ([Status__c] ASC)

