DROP TABLE IF EXISTS OTEXA_SCHEDULEB_CATEGORY_REF
CREATE TABLE OTEXA_SCHEDULEB_CATEGORY_REF (
	[SCHEDULE_B]      [varchar](25) NULL,
	[CAT_ID]          [varchar](3) NULL,
)
GO


DROP TABLE IF EXISTS [dbo].[OTEXA_SCHEDULEB_CHAPTER_CATEGORY_REF]
CREATE TABLE [dbo].[OTEXA_SCHEDULEB_CHAPTER_CATEGORY_REF](
	[CHAPTER]     [varchar](25) NULL,
	[SCHEDULE_B]  [varchar](25) NULL,
	[CAT_ID]      [varchar](3) NULL
)
GO


DROP TABLE IF EXISTS [dbo].[OTEXA_SCHEDULEB_CAT_REF]
CREATE TABLE [dbo].[OTEXA_SCHEDULEB_CAT_REF](
	[SCHEDULE_B]   [varchar](25) NULL, 
	[CAT_ID]       [varchar](3) NULL
)
GO
